package MusicBase.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;
  public static Object propertyMacro_GetPropertyValue_5071094092909982220(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xb4c83bfcbf224ef3L, 0x95393d39b490a670L, 0x46602535ae7258ceL, 0x46602535ae730ef1L, "key")) + SPropertyOperations.getInteger((SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0xb4c83bfcbf224ef3L, 0x95393d39b490a670L, 0x46602535ae77d00eL, "MusicBase.structure.Song"))), MetaAdapterFactory.getProperty(0xb4c83bfcbf224ef3L, 0x95393d39b490a670L, 0x46602535ae77d00eL, 0x46602535ae975c46L, "transpose"));
  }
  public static Object propertyMacro_GetPropertyValue_5071094092910030514(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xb4c83bfcbf224ef3L, 0x95393d39b490a670L, 0x46602535ae7258ceL, 0x46602535ae730ef3L, "duration"));
  }
  public static Object propertyMacro_GetPropertyValue_5071094092909818293(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Player";
  }
  public static Iterable<SNode> sourceNodesQuery_5071094092909975338(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xb4c83bfcbf224ef3L, 0x95393d39b490a670L, 0x46602535ae77d00eL, 0x46602535ae77d00fL, "notes"));
  }
}
