package MusicBase.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Note_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPlayable_BehaviorDescriptor {
  public Note_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "MusicBase.structure.Note";
  }
}
