package MusicBase.sandbox;

/*Generated by MPS */

import MusicBase.runtime.MidiPlayerBase;

public class KinderliedPlayer extends MidiPlayerBase {
  public static void main(String[] args) {
    KinderliedPlayer myself = new KinderliedPlayer();
    myself.run(args);
  }

  public void run(String[] args) {
    init(true);
    play(50, 500);
    play(52, 500);
    play(54, 500);
    play(55, 500);
    play(57, 1000);
    play(57, 1000);
    play(59, 500);
    play(59, 500);
    play(59, 500);
    play(59, 500);
    play(57, 2000);
    play(59, 500);
    play(59, 500);
    play(59, 500);
    play(59, 500);
    play(57, 2000);
    play(55, 500);
    play(55, 500);
    play(55, 500);
    play(55, 500);
    play(54, 1000);
    play(54, 1000);
    play(57, 500);
    play(57, 500);
    play(57, 500);
    play(57, 500);
    play(50, 2000);
  }

  private void play(int key, int duration) {
    //  add play code here 
    noteOn(key);
    try {
      Thread.sleep(duration);
    } catch (InterruptedException e) {
    }
    noteOff(key);
  }
}
