package MusicBase.runtime;

/*Generated by MPS */

import javax.sound.midi.Synthesizer;
import javax.sound.midi.MidiChannel;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;

public class MidiPlayerBase {
  private Synthesizer synth = null;
  private MidiChannel channel = null;
  private boolean verbose = false;

  public boolean init(boolean verbose) {
    this.verbose = verbose;
    System.out.println("MidiPlayer init");
    try {
      synth = MidiSystem.getSynthesizer();
      synth.open();

      channel = synth.getChannels()[0];
    } catch (MidiUnavailableException e) {
      e.printStackTrace();
      return false;
    }

    return true;
  }
  public void noteOn(int key) {
    if (verbose) {
      System.out.println("MidiPlayerBase: noteOn " + key);
    }
    channel.noteOn(key, 127);
  }
  public void noteOff(int key) {
    if (verbose) {
      System.out.println("MidiPlayerBase: noteOff " + key);
    }
    channel.noteOff(key);
  }
}
