package JavaModel;

/*Generated by MPS */

import javax.sound.midi.Synthesizer;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.MidiChannel;

public class Test1 {
  public static void main(String[] args) {
    System.out.println("Hello World!");

    Synthesizer synth = null;
    try {
      synth = MidiSystem.getSynthesizer();
      synth.open();

    } catch (MidiUnavailableException e) {
    }
    MidiChannel channel = null;
    if (synth != null) {
      channel = synth.getChannels()[0];
      channel.noteOn(80, 127);
      channel.noteOn(84, 127);
    }

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
    }

    if (channel != null) {
      channel.noteOff(80);
    }

    System.out.println("Ready!");
  }
}
